### ISSUE TITLE
Blackscreen but can open Inventory

### ISSUE THREAD

**Issue by Rimusp** [decce6/Gnetum#5]
So after joining a World everything is Black except for the Hotbar and the Inventory.

Hotbar stays the same like its an image.

Also Log is massive: https://drive.google.com/file/d/1vZNtM2dKQf7YnN8gb7pCDfLC8KbedeLE/view?usp=sharing

I saw renderlib and nothirium in the log but those work in an instance with just them and gnetum.

**Comment by decce6** [comment]
The log spam is not relevant with Gnetum. You have enabled OpenGL debug output in RenderLib config but it has some issues with your setup for some reason.

Can you try with Gnetum 1.1.2? This version fixes some mod incompatibilities. If it's still not working please post your mod list so I can investigate further.

**Comment by Rimusp** [comment]
Found the Issue its ScalingGUI: https://www.curseforge.com/minecraft/mc-mods/scalingguis

[latest.log](https://github.com/user-attachments/files/19609495/latest.log)

**Comment by decce6** [comment]
Thanks for finding out the mod causing the issue. Can you try if this build fixes the issue? https://github.com/decce6/Gnetum/actions/runs/14276518068

**Comment by Rimusp** [comment]
Yup is fixed Thank you!

**Comment by CalaMariGold** [comment]
I'm having a black screen as well but that build didn't fix it for me. I'm not using scalingguis so it's likely another mod.

Mod list: https://mclo.gs/nSkUpdh

**Comment by CalaMariGold** [comment]
Black screen also occurs when timer is low in [Time Is Up](https://github.com/Naturaspell/TimeIsUp) mod

**Comment by decce6** [comment]
Hi @CalaMariGold, the black screen issue that occurs when the timer is low in Time is up mod has been fixed in 1.2.0.

Regarding the blackscreen with the long list of mods, can you please provide a screenshot of the HUD *without* Gnetum, so I can know what mods are modifying the HUD and so I don't have to download and check all those many mods manually. Or if this is a publicly available modpack, a link to the pack would be helpful.

**Comment by CalaMariGold** [comment]
Tested on 1.2.0, same issue. Here's the repo for the pack and branch we're using. https://github.com/Rebirth-of-the-Night/Rebirth-of-the-Night/tree/Cleanroom-Testing

Two mods come to mind, Better HUD and Console Experience.

**Comment by decce6** [comment]
Better HUD seems to be quite invasive in that it completely cancels rendering of vanilla HUD elements and instead renders them in its own event listener. This means when it renders the vignette, the screen will go black because of the use of an incorrect blending function. It's difficult to fix this in Gnetum, but I'll still look into this.

I'm going to close this issue as the original incompatibility (with ScalingGuis mod) has been fixed. The incompatibility with Better HUD will be tracked in #13.

**Comment by decce6** [comment]
@CalaMariGold Time Is Up compatibility should be fixed in 1.3.3, though I didn't test with other mods. Would love to know if it works on your side!

**Comment by CalaMariGold** [comment]
@decce6 Black screen still occurs in RotN on 1.3.5
modlist.txt: https://gnomebot.dev/paste/mclogs/24s79zO

**Comment by decce6** [comment]
@CalaMariGold Should be fixed in 1.4.0
